### ISSUE TITLE
0.0.9 release

### ISSUE THREAD

**Issue by chrisfrank** [Airtable/airtable-ruby#13]
I'm working on a gem that needs 0.0.9's Airtable::Table.update_record_fields method. Could you publish 0.0.9 to RubyGems please?

FWIW, here's the gem I'm working on: https://github.com/chrisfrank/airmodel

It currently monkeypatches airtable-ruby 0.0.8 with your update_record_fields method, but I'd like to remove that code from my gem as soon as I can. Thanks!

**Comment by syrnick** [comment]
Done. There was no reason to hold that off. Let me know if you have any issues.

Re airmodel, that looks nice! Keep us posted of your progress!

**Comment by chrisfrank** [comment]
Thanks!

**Comment by sbauch** [comment]
@chrisfrank would be curious to see how you are using this in a rails application, particularly with caching.

I've done some similar stuff by including `ActiveModel::Model` in my Airtable model classes, but I'm still not super happy with my caching.

Any chance you've got a blog post coming or something?

**Comment by chrisfrank** [comment]
@sbauch I haven't used this in Rails yet, and I'm not sure I would, since Rails includes full SQL support. But it's been working well in Sinatra. I'm using this gem + memcached in a project that launches next week, and will publish a writeup as soon as I can after we launch. Thanks for your interest.
